# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ib7sa8O-Zf9Hd7bpFBI0bAJPLm90zSFb
"""

array_number = ["月曜日は晴れです", "火曜日は雨です", "水曜日は晴れです", "木曜日は晴れです", "金曜日は曇りです", "土曜日は曇りのち雨です", "日曜日は雷雨です"]
print(array_number[2])

dictionary = {"mon":"晴れ","tue":"雨","wed":"晴れ","thu":"晴れ","fri":"曇り","sat":"曇りのち雨","sun":"雷雨"}
print(dictionary["wed"])